version: '3'
services:
        redis-server:
                image: redis:alpine
                volumes:
                        - data:/data
                command: ["redis-server", "--appendonly", "yes"]
        node-app: 
                build: .
                ports:
                        - "4001:8081"
volumes:
        data:
