version: "3.7"
services:
        doku:
                build: .
                ports:
                        - "80:80"
                volumes:
                        - type: bind
                          source: ./dokuwiki
                          target: /var/www/html
                          volume:
                                nocopy: true
volumes:
        dokuwiki:   