node {
    stage('Clone Sources') {
        git url: 'https://github.com/TuVanNguyen/DevOpsTutorials.git'
    }
    stage('Build Image') {
        app = docker.build('test-image',"DevOpsTutorial/Jenkins/myDockerfile")
    }
    stage('Test'){
        docker.image('test-image').withRun('-p 8082:80') { c ->
            sh 'curl http://localhost:8082'
        }
    }    
}
